version: '3.8'

services:
  web:
    build: ./app
    container_name: flask_web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
